# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/accueil.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(1081, 917)
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1081, 901))
        self.label.setStyleSheet("border : 1px solid gray;\n"
"background-image : url(:/img/static/bienvenue-arriere-plan-ecole-articles-elements-scolaires-feuille-papier-feuilles-automne-stylos-crayons-pinceaux-loupe-table-bois_149267-1153.jpeg)")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/static/20210206_143049.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 50, 661, 111))
        self.label_2.setStyleSheet("background: rgb(255, 218, 199);\n"
"border-radius:15px;\n"
"font-size : 30px;\n"
"\n"
"    \n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 80, 81, 61))
        self.label_5.setStyleSheet("background-image : url(:/img/static/4696758.png)")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/img/static/4696758.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.projets_btn = QtWidgets.QPushButton(self.centralwidget)
        self.projets_btn.setGeometry(QtCore.QRect(760, 660, 231, 131))
        self.projets_btn.setStyleSheet("QPushButton{\n"
"background: rgb(255, 218, 199);\n"
"border-radius:10px;\n"
"font-size : 30px;\n"
"text-align:right;\n"
"image:url(:/img/static/4696798.png);\n"
"padding: 40px;\n"
"image-position:left;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(223, 186, 168);\n"
"border-radius:10px;\n"
"font-size : 30px;\n"
"}")
        self.projets_btn.setObjectName("projets_btn")
        self.cretion_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cretion_btn.setGeometry(QtCore.QRect(120, 660, 271, 131))
        self.cretion_btn.setStyleSheet("QPushButton{\n"
"background: rgb(255, 218, 199);\n"
"border-radius:10px;\n"
"font-size : 30px;\n"
"text-align:right;\n"
"image:url(:/img/static/4696755.png);\n"
"padding: 40px;\n"
"image-position:left;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(223, 186, 168);\n"
"border-radius:10px;\n"
"font-size : 30px;\n"
"}")
        self.cretion_btn.setObjectName("cretion_btn")
        Home.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Home)
        self.statusbar.setObjectName("statusbar")
        Home.setStatusBar(self.statusbar)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "MainWindow"))
        self.label_2.setText(_translate("Home", "Transcription D\'Image"))
        self.projets_btn.setText(_translate("Home", "Projets"))
        self.cretion_btn.setText(_translate("Home", "Création"))
import ressource_rc
