# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/listeHisto.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListHisto(object):
    def setupUi(self, ListHisto):
        ListHisto.setObjectName("ListHisto")
        ListHisto.resize(934, 644)
        ListHisto.setStyleSheet("background : white;")
        self.centralwidget = QtWidgets.QWidget(ListHisto)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(80, 120, 741, 341))
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 20, 521, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("background: rgb(255, 218, 199);\n"
"font-size : 30px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 71, 71))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/img/static/860812.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 500, 31, 41))
        self.label_3.setStyleSheet("background-image : url(:/img/static/4696755.png)")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/img/static/4696755.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.modifier_btn = QtWidgets.QPushButton(self.centralwidget)
        self.modifier_btn.setGeometry(QtCore.QRect(570, 500, 181, 71))
        self.modifier_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 218, 199);\n"
"border-radius:10px;\n"
"font-size : 20px;\n"
"image:url(:/img/static/4696755.png);\n"
"image-position:left;\n"
"text-align:right;\n"
"padding:20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(223, 186, 168);\n"
"\n"
"}")
        self.modifier_btn.setObjectName("modifier_btn")
        self.creerDoc_btn = QtWidgets.QPushButton(self.centralwidget)
        self.creerDoc_btn.setGeometry(QtCore.QRect(90, 490, 261, 81))
        self.creerDoc_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 218, 199);\n"
"border-radius:10px;\n"
"font-size : 20px;\n"
"image:url(:/img/static/1828926.png);\n"
"image-position:left;\n"
"text-align:right;\n"
"padding:20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(223, 186, 168);\n"
"\n"
"}")
        self.creerDoc_btn.setObjectName("creerDoc_btn")
        ListHisto.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ListHisto)
        self.statusbar.setObjectName("statusbar")
        ListHisto.setStatusBar(self.statusbar)

        self.retranslateUi(ListHisto)
        QtCore.QMetaObject.connectSlotsByName(ListHisto)

    def retranslateUi(self, ListHisto):
        _translate = QtCore.QCoreApplication.translate
        ListHisto.setWindowTitle(_translate("ListHisto", "MainWindow"))
        self.label.setText(_translate("ListHisto", "Historique des Documents"))
        self.modifier_btn.setText(_translate("ListHisto", "Modifier"))
        self.creerDoc_btn.setText(_translate("ListHisto", "Créer Un Document"))
import ressource_rc
