# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/transform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Transform(object):
    def setupUi(self, Transform):
        Transform.setObjectName("Transform")
        Transform.resize(1252, 1002)
        Transform.setStyleSheet("QMainWindow{\n"
"    background:rgb(140, 141, 141);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Transform)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1251, 981))
        self.widget.setStyleSheet("border : 1px solid black;\n"
"background: white;")
        self.widget.setObjectName("widget")
        self.champ_image = QtWidgets.QLabel(self.widget)
        self.champ_image.setGeometry(QtCore.QRect(10, 130, 441, 681))
        self.champ_image.setStyleSheet("border:1px solid black;\n"
"border-radius:10px;")
        self.champ_image.setText("")
        self.champ_image.setObjectName("champ_image")
        self.champTexte = QtWidgets.QTextEdit(self.widget)
        self.champTexte.setGeometry(QtCore.QRect(670, 110, 561, 731))
        self.champTexte.setStyleSheet("border-radius:10px;")
        self.champTexte.setObjectName("champTexte")
        self.nombreTotalImage = QtWidgets.QLabel(self.widget)
        self.nombreTotalImage.setGeometry(QtCore.QRect(370, 60, 81, 51))
        self.nombreTotalImage.setStyleSheet("border-radius:10px;\n"
"font-size : 30px;")
        self.nombreTotalImage.setAlignment(QtCore.Qt.AlignCenter)
        self.nombreTotalImage.setObjectName("nombreTotalImage")
        self.numeroPage = QtWidgets.QLineEdit(self.widget)
        self.numeroPage.setGeometry(QtCore.QRect(140, 60, 91, 51))
        self.numeroPage.setStyleSheet("border-radius:10px;\n"
"font-size : 30px;")
        self.numeroPage.setText("")
        self.numeroPage.setAlignment(QtCore.Qt.AlignCenter)
        self.numeroPage.setObjectName("numeroPage")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 121, 51))
        self.label_5.setStyleSheet("font-size : 30px;\n"
"border-radius:10px;\n"
"background: rgb(255, 218, 199);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(240, 60, 121, 51))
        self.label_6.setStyleSheet("font-size : 30px;\n"
"border-radius:10px;\n"
"background: rgb(255, 218, 199);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.supprPhoto_btn = QtWidgets.QPushButton(self.widget)
        self.supprPhoto_btn.setGeometry(QtCore.QRect(170, 850, 61, 51))
        self.supprPhoto_btn.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:10px;\n"
"image: url(:/img/static/98116.png);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background:rgb(203, 201, 204);\n"
"}")
        self.supprPhoto_btn.setText("")
        self.supprPhoto_btn.setObjectName("supprPhoto_btn")
        self.ajoutPhoto_btn = QtWidgets.QPushButton(self.widget)
        self.ajoutPhoto_btn.setGeometry(QtCore.QRect(240, 850, 61, 51))
        self.ajoutPhoto_btn.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:10px;\n"
"image : url(:/img/static/1828926.png);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background:rgb(203, 201, 204);\n"
"}")
        self.ajoutPhoto_btn.setText("")
        self.ajoutPhoto_btn.setObjectName("ajoutPhoto_btn")
        self.suivant_btn = QtWidgets.QPushButton(self.widget)
        self.suivant_btn.setGeometry(QtCore.QRect(360, 831, 81, 81))
        self.suivant_btn.setStyleSheet("QPushButton{\n"
"background: rgb(255, 218, 199);\n"
"border-radius:10px;\n"
"font-size : 30px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(223, 186, 168);\n"
"border-radius:10px;\n"
"font-size : 30px;\n"
"}")
        self.suivant_btn.setObjectName("suivant_btn")
        self.precedent_btn = QtWidgets.QPushButton(self.widget)
        self.precedent_btn.setGeometry(QtCore.QRect(40, 830, 81, 81))
        self.precedent_btn.setStyleSheet("QPushButton{\n"
"background: rgb(255, 218, 199);\n"
"border-radius:10px;\n"
"font-size : 30px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(223, 186, 168);\n"
"border-radius:10px;\n"
"font-size : 30px;\n"
"}")
        self.precedent_btn.setObjectName("precedent_btn")
        self.sauvegarde_btn = QtWidgets.QPushButton(self.widget)
        self.sauvegarde_btn.setGeometry(QtCore.QRect(850, 870, 281, 61))
        self.sauvegarde_btn.setStyleSheet("QPushButton{\n"
"background: rgb(255, 218, 199);\n"
"border-radius:10px;\n"
"font-size : 30px;\n"
"image:url(:/img/static/4696820.png);\n"
"padding: 10px;\n"
"image-position:left;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(223, 186, 168);\n"
"border-radius:10px;\n"
"font-size : 30px;\n"
"}")
        self.sauvegarde_btn.setIconSize(QtCore.QSize(16, 16))
        self.sauvegarde_btn.setObjectName("sauvegarde_btn")
        self.transcrire_btn = QtWidgets.QPushButton(self.widget)
        self.transcrire_btn.setGeometry(QtCore.QRect(460, 440, 201, 61))
        self.transcrire_btn.setStyleSheet("QPushButton{\n"
"background: rgb(255, 218, 199);\n"
"border-radius:10px;\n"
"font-size : 30px;\n"
"image:url(:/img/static/4892322.png);\n"
"padding: 11px;\n"
"image-position:left;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(223, 186, 168);\n"
"border-radius:10px;\n"
"font-size : 30px;\n"
"}")
        self.transcrire_btn.setIconSize(QtCore.QSize(16, 16))
        self.transcrire_btn.setObjectName("transcrire_btn")
        Transform.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Transform)
        self.statusbar.setObjectName("statusbar")
        Transform.setStatusBar(self.statusbar)

        self.retranslateUi(Transform)
        QtCore.QMetaObject.connectSlotsByName(Transform)

    def retranslateUi(self, Transform):
        _translate = QtCore.QCoreApplication.translate
        Transform.setWindowTitle(_translate("Transform", "MainWindow"))
        self.nombreTotalImage.setText(_translate("Transform", "10"))
        self.label_5.setText(_translate("Transform", "Page"))
        self.label_6.setText(_translate("Transform", "Sur"))
        self.suivant_btn.setText(_translate("Transform", ">>"))
        self.precedent_btn.setText(_translate("Transform", "<<"))
        self.sauvegarde_btn.setText(_translate("Transform", "Sauvegarder"))
        self.transcrire_btn.setText(_translate("Transform", "    Transcrire"))
import ressource_rc
